name: Deploy

on:
  workflow_call:
    inputs:
      framework: 
        description: '.net framework'
        type: string
        required: true
      branch:
        description: 'Git branch used for this build'
        type: string
        required: true
      major_version:
        description: 'Sonarr major version'
        type: string
        required: true
      version:
        description: 'Sonarr version'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      framework: 
        description: '.net framework'
        type: string
        required: true
      branch:
        description: 'Git branch used for this build'
        type: string
        required: true
      major_version:
        description: 'Sonarr major version'
        type: string
        required: true
      version:
        description: 'Sonarr version'
        type: string
        required: true

jobs:
  package:
    strategy:
      matrix:
        platform: [linux] # [freebsd, linux, macos, windows]
        include:
          # - platform: freebsd
          #   os: ubuntu-latest
          - platform: linux
            os: ubuntu-latest
          # - platform: macos
          #   os: ubuntu-latest
          # - platform: windows
          #   os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Package
      uses: ./.github/actions/package
      with:
        framework: ${{ inputs.framework }}
        platform: ${{ matrix.platform }}
        artifact: build_${{ matrix.platform }}
        branch: ${{ inputs.branch }}
        major_version: ${{ inputs.major_version }}
        version: ${{ inputs.version }}

  release:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Download release artifacts
      uses: actions/download-artifact@v4
      with:
        path: _artifacts
        pattern: release_*
        merge-multiple: true

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: _artifacts/Sonarr.*
        commit: ${{ github.sha }}
        generateReleaseNotes: true
        name: ${{ inputs.version }}
        prerelease: ${{ inputs.branch != 'develop' && inputs.branch != 'main' }}
        skipIfReleaseExists: true
        tag: v${{ inputs.version }}

  docker:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Date
        id: date
        run: echo "::set-output name=BUILD_DATE::$(date '+%Y-%m-%dT%H:%M:%S%:z')"

      - name: Publish to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./docker
          tags: |
            ghcr.io/piracygit/sonarr:latest
            ghcr.io/piracygit/sonarr:${{ inputs.branch }}
            ghcr.io/piracygit/sonarr:v${{ inputs.version }}
          build-args: |
            VERSION=2.1
            SONARR_VERSION=${{ inputs.version }}
            BUILD_DATE=${{ steps.date.outputs.BUILD_DATE }}
          driver-opts:
            image=moby/buildkit:v0.10.6
          cache-from: type=gha
          cache-to: type=gha,mode=max
