name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          base: develop
          head: develop
